# BIH HPC (cubi) â€” SLURM executor plugin.
# Requires: pip install snakemake-executor-plugin-slurm
executor: slurm
jobs: 100
latency-wait: 60

default-resources:
  slurm_partition: medium
  slurm_account: scholl-lab
  mem_mb_per_cpu: 4400
  runtime: 120
