name: variantcentrifuge
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bcftools=1.21=h8b25389_0
  - bedtools=2.31.1=h13024bc_3
  - igv-reports=1.14.1=pyh7e72e81_0
  - python=3.12.8=h9e4cc4f_1_cpython
  - snpeff=5.2=hdfd78af_1
  - snpsift=5.2=hdfd78af_0
  - pandas=2.2.3=py312hf9745cd_1
  - scipy=1.14.1=py312h62794b6_2
  - statsmodels=0.14.4=py312hc0a28a1_0
  - openpyxl=3.1.5=py312h710cb58_1
  - jinja2
  - psutil
  - numpy
  # Development dependencies
  - black=24.4.0
  - flake8=7.0.0
  - pre-commit=3.6.2
  - isort=5.13.2
  - pytest=8.1.1
  - pytest-cov=4.1.0
  - pytest-mock=3.12.0
  # Documentation dependencies
  - sphinx>=7.0.0
  - furo
  - myst-parser
  - sphinx-autodoc-typehints
  - pip:
    - intervaltree
    - smart-open
    - -e .
