# Charite HPC â€” SLURM executor plugin.
# Max walltime: 2 days (2880 min) on all partitions.
# Requires: pip install snakemake-executor-plugin-slurm
executor: slurm
jobs: 50
latency-wait: 60

software-deployment-method:
  - conda

default-resources:
  slurm_partition: compute
  slurm_account: sc-users
  mem_mb: 4400
  runtime: 120
